---
- name: Install tmux
  block:
    - name: Include OS-specific variables
      include_vars: "{{ var_file }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: var_file

    - name: Install OS-specific dependencies
      ansible.builtin.include_tasks: "{{ var_file }}"
      with_first_found:
        - "noauto_install_dep_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_install_dep_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_install_dep_{{ ansible_distribution }}.yml"
        - "noauto_install_dep_{{ ansible_os_family }}.yml"
        - "noauto_install_dep_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: var_file

    - name: Install tmux
      ansible.builtin.include_tasks:
        file: noauto_install_{{ tmux_install_method }}.yml
