---
- name: Add tmux config file
  block:
    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ tmux_config_dir }}"
        state: directory
        mode: "0750"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add tmux config file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/tmux.conf.j2"
        dest: "{{ tmux_config_file }}"
        mode: "0750"
