---
- name: Ensure plugin folder exists
  ansible.builtin.file:
    path: "{{ tmux_plugin_dir }}"
    state: directory
    mode: "0750"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone tpm repository
  ansible.builtin.git:
    repo: "{{ tmux_plugin_tpm_repo }}"
    dest: "{{ tmux_plugin_dir }}/tpm"
    update: false
    version: "v{{ tmux_plugin_tpm_version }}"
  become: false

- name: Check if tmux plugins are installed
  ansible.builtin.stat:
    path: "{{ tmux_plugin_dir }}/{{ plugin.name }}"
  register: tmux_plugin_stat
  loop: "{{ tmux_plugins }}"
  loop_control:
    loop_var: plugin

- name: Install missing tmux plugins
  ansible.builtin.command:
    cmd: "{{ tmux_plugin_dir }}/tpm/bin/install_plugins"
  register: tmux_plugins_install
  changed_when: "'download success' in tmux_plugins_install.stdout"
  when: tmux_plugin_stat.results | selectattr('stat.exists', 'equalto', false) | list | length > 0
