---
- name: Converge
  hosts: all

  vars:
    ansible_user: root
    tmux_plugins:
      - name: "vim-tmux-navigator"
        namespace: "christoomey"
    tmux_prefix: "C-a"
    tmux_key_bindings:
      - key: "C-l"
        command: "send-keys 'C-l'"
      - key: "C-y"
        flags: "-n"
        command: >-
          copy-mode \;
          send-keys -X cursor-up \;
          send-keys -X cursor-up \;
          send-keys -X search-backward "$USER"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.tmux
